name: Build HTML Docker Image

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t html-site .

      # Optional: Run container and test (use curl or health checks)
      - name: Test container locally
        run: |
          docker run -d -p 8080:80 --name html-test html-site
          sleep 5
          curl -f http://localhost:8080 || (docker logs html-test && exit 1)
